name: Daily Weather Update

on:
  schedule:
    # Changed to run daily at 08:00 PM UTC instead of 10:00 AM UTC - 
    - cron: '0 20 * * *'
  workflow_dispatch: # Allows manual execution if needed

permissions:
  contents: write # Grant write permissions to push changes

jobs:
  weather-update:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Clone Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true # Ensures credentials are available for pushing changes

    # Step 2: Set up Python (if needed by the script)
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies (if required)
    - name: Install Dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found, skipping dependencies installation."
        fi

    # Step 4: Run the weather.sh script. Add x (execute file permission) to the file if needed.
    - name: Run Weather Script
      run: |
        chmod +x weather.sh
        ./weather.sh

    # Step 5: Commit and push changes back to the repository
    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Daily weather data update: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main
